# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - EcoGuardian

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_54a733f9440f4f649b14ec4a66384b7c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_13b442b71e1e4eeca8de3c2ae022adfb }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: index.docker.io/gustavohuilca/ecoguardian:${{ github.sha }}
        file: EcoGuardian-Backend/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
            app-name: 'EcoGuardian'
            slot-name: 'Production'
            publish-profile: ${{ secrets.AzureAppService_PublishProfile_bacbe6dea3ab415e86ab74115e206d85 }}
            images: 'index.docker.io/gustavohuilca/ecoguardian:${{ github.sha }}'
